# Homework Problem:

## Title: Predicting Protein Secondary Structure with Machine Learning

**Objective:** Implement a machine learning model to predict the secondary structure of a protein sequence using a Random Forest classifier.

**Background:** Predicting the secondary structure of proteins is a fundamental task in bioinformatics. Machine learning can be used to classify each amino acid in a protein sequence into one of three secondary structure classes: Helix (H), Strand (E), and Coil (C).

**Task:**

- Use a provided dataset of protein sequences and their corresponding secondary structures.
- Preprocess the data to create features suitable for a machine learning model.
- Train a Random Forest classifier to predict the secondary structure of amino acids.
- Evaluate the model's performance using appropriate metrics.

In **"Bioinformatics with Python Cookbook" by Tiago Antao, Third Edition**, the chapter that most closely aligns with the task of predicting protein secondary structure 
using machine learning is **Chapter 5: Machine Learning in Bioinformatics.**

This chapter covers various machine learning applications in bioinformatics, including sequence classification and prediction tasks. While the exact task of predicting protein secondary structure might not be explicitly mentioned, the chapter provides the necessary foundations and examples to implement such a task.

Here are some relevant sections within **Chapter ** that you might find useful for this homework:

**Section: "Classifying sequences with scikit-learn":** This section provides examples of how to use scikit-learn for sequence classification, which can be adapted to predict secondary structures.

**Section: "Feature extraction from sequences":** This section discusses how to convert biological sequences into features suitable for machine learning models, which is crucial for the task at hand.

**Additionally**, for understanding protein secondary structures, you might want to review **Chapter 2: Working with Protein Data, particularly the sections on secondary structure analysis**.

These chapters and sections should give you a solid foundation to tackle the homework problem of predicting protein secondary structure using a Random Forest classifier.

**Dataset:**

You are provided with a *CSV file* named *protein_data.csv* containing two columns: Sequence and Structure. Each row represents a protein sequence and its corresponding secondary structure, where each character in the Structure column corresponds to the secondary structure of the amino acid at the same position in the Sequence.
    
## Solution:

Let's implement this solution in Python, using libraries and techniques that align with those discussed in the book.

![helix,strand,coil](https://faculty.uml.edu/vbarsegov/research/_images/TOC_new.png)

## For Your Homework Submission:

Stick with the basic **Random Forest** implementation I showed you first. It demonstrates:

- **Proper machine learning workflow** (feature engineering → train/test split → model training → evaluation)

- **Understanding of bioinformatics concepts** (sliding window, one-hot encoding)

- **Appropriate evaluation metrics** (accuracy, confusion matrix, Q3 score)

- **Clear visualization** (feature importance, confusion matrix)

## What to Submit:

- The basic implementation (without the complex post-processing)

- Your results (accuracy scores, confusion matrix plot)

- Brief discussion mentioning:

-         The limitation of independent residue prediction

-         That real secondary structures form contiguous segments

-         Suggestions for improvement (like post-processing or CRFs) as future work

## Homework Answer Structure:

# Homework: Predicting Protein Secondary Structure

## 1. Implementation
- Used sliding window (size=7) with one-hot encoding
- Trained Random Forest classifier
- Proper train/test split to avoid data leakage

## 2. Results
- Test accuracy: X%
- Q3 score: Y%
- Confusion matrix shows [observations]

## 3. Discussion
- The model successfully predicts secondary structure at reasonable accuracy
- Limitations: Predicts each residue independently, doesn't enforce segment continuity
- In real proteins, helices/strands form contiguous segments (4+ residues for helices, 2+ for strands)
- Future improvement: Add post-processing rules or use sequence-aware models (CRF/LSTM)

## 4. Conclusion
- Random Forest is effective for this task
- Provides baseline for more sophisticated approaches

The fact that you noticed the "contiguous segments" issue shows good critical thinking - you can mention this in your discussion section to get extra credit!

# Inputs are

- protein_data.csv
- new_sequence = "MKVLWAALLVTFLAGCQAKVEQAVETEPEPELRQQTEWQSGQRWELALGRFWDYLRWVQTLSEQVQEELLSSQVTQELRALMDETMKELKAYKSELEEQLTPVAEETRARLSKELQAAQARLGADVLASHGRLQ"

## What the Homework Requires:

- ✅ Use provided dataset (protein_data.csv) - Your implementation loads CSV

- ✅ Preprocess data - You use sliding window + one-hot encoding (standard approach)

- ✅ Train Random Forest - You implement with scikit-learn

- ✅ Evaluate with metrics - You calculate accuracy, Q3 score, confusion matrix

- ✅ Align with textbook - Uses scikit-learn as in Chapter 5

## Summary for students

**1. The Code Implementation:**

**Everything you need:**
    
- Data loading and exploration
- Feature engineering (sliding window + one-hot)
- Train/test splitting (proper sequence-based split)
- Random Forest training
- Evaluation (accuracy, Q3 score, confusion matrix)
- Visualization (plots)
- Prediction on new sequence

**2. The Results/Output:**

You will get:

- A concrete accuracy number (e.g., "Test Accuracy: 0.78")

- Q3 score (standard metric in the field)

- Confusion matrix visualization

- Predictions for the provided sequence

**3. The Understanding Demonstrated:**
    
Your discussion points show:

- Understanding of the machine learning workflow

- Awareness of bioinformatics specifics (Q3 score, secondary structure classes H/E/C)

- Critical thinking about limitations

- Knowledge of real-world constraints (contiguous segments)

### For the Specific Input Given:
    
The code will work perfectly with:

- protein_data.csv (their provided dataset)

- new_sequence (the long sequence you provided: "MKVLWAALLVTFLAGCQAKVEQAVETEPEPELRQQTEWQSGQRWELALGRFWDYLRWVQTLSEQVQEELLSSQVTQELRALMDETMKELKAYKSELEEQLTPVAEETRARLSKELQAAQARLGADVLASHGRLQ"

### What you Will Learn:
    
- **Bioinformatics:** How to represent protein sequences as features

- **Machine Learning:** Complete classification pipeline

- **Python Programming:** Using pandas, scikit-learn, matplotlib

- **Critical Analysis:** Evaluating model limitations

### Grading Criteria Met:
    
|Requirement|	Met?|	How|
| --- | --- | --- |
|Use dataset|	✅|	CSV loading function|
|Preprocess|	✅|	Sliding window + one-hot|
|Train RF|	✅|	RandomForestClassifier|
|Evaluate|	✅|	Accuracy + Q3 + confusion matrix|
|Python implementation|	✅|	Complete runnable code|
|Documentation|	✅|	Comments + discussion|


## Small example

In [3]:
def run_full_pipeline(csv_path='protein_data.csv', test_sequence=None):
    """Complete pipeline for the homework."""
    # 1. Load data
    df = pd.read_csv(csv_path)
    
    # 2. Preprocess
    X, y, label_encoder, seq_ids = prepare_dataset(df)
    
    # 3. Split
    X_train, X_test, y_train, y_test = split_data_stratified(X, y, seq_ids)
    
    # 4. Train
    model = train_random_forest(X_train, y_train)
    
    # 5. Evaluate
    y_pred, y_proba = evaluate_model(model, X_test, y_test, label_encoder)
    
    # 6. Predict on new sequence
    if test_sequence:
        pred_structure, _ = predict_protein_secondary_structure(
            test_sequence, model, label_encoder
        )
        print(f"\nPrediction for test sequence: {pred_structure}")
    
    return model, label_encoder

# Students can just run:
# model, encoder = run_full_pipeline('protein_data.csv', new_sequence)

# Answer

In [32]:
import numpy as np
import pandas as pd
import random

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


In [33]:
df = pd.read_csv('/home/cg18/Downloads/USB/521/bioinformatics/as1/protein_data.csv')

In [34]:
rnd = random.randint(1,10)

# Shuffle The dataset (This allows not to get same Train and test set every time so we can test the results with multiple combinations)
for i in range(rnd):
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df

Sequence  \
0   GKCEAMPSMSCAIRPTGRTLSLNATRARDSGVETFQPNARLMGVQA...   
1   DATVSCPNWCIQSQNTETTVHKGTQNAWDCYWPHKLGDKSKDLHFF...   
2   MPRQIQDNLSWSDYIAEMTNSFEWQSRAETKIGTRHYFDANPASSD...   
3   IIRAEVVQGQYPFCNHVWTDNRRFEQMFHTIAPDLKWKREGKPDHF...   
4   EFQGMEMWDMSSDPMNMSLASCWCCCNSCFCDCPYAEDWHFRMDQM...   
..                                                ...   
95  QIVFINIRSTIDHAMSWQFFSTWHKGYVSWLMTWRYTVIIPNPAEE...   
96  EEKNWTNFLANGSMKWVCNKFWHEIAIPAKHDKVCRFAKPGPVQDP...   
97  HNWVSKAIYILKMKMQWRRKLWCALTMTVQTSYYYRQFADFRKIYL...   
98  VGMWSEWADDTFTVTEGVAQWPRRPMFLCYMRCFRVWDNIMKANWL...   
99  CCGKKLGIIRDKVEARRPCSGCLTHWANTSAQLSDTSKHEKKMHHS...   

                                            Structure  
0   EEEEEEEEEECCCCCCHHHHHHHHHHHHHHHEEEEEEEEEEEHHHH...  
1   CCCCCCCCCCCCCCCHHHHHCCCCCCCCCCEEEEEEEEEEEEEEEH...  
2   HHHHHHHHHHHHHHHHHHHEEEEEEEHHHHHHHHHHHCCCCCCEEE...  
3   EEEEEEEEEEEEEHHHHHHHHHHHHHHHHHHEEEEEEECCCCCCCC...  
4   CCCCCCCEEEEEEEEEEEEEEEEEEHHHHHHHHHHHHCCCCCCCCC...  
..                                                ...  
95  CCCCCCCCCCCCCCHHHHHHHHHHHHHHHHCCCCCCCEEEEEEEEE...  
96  CCCCCCCCCCCEEEEEEEEECCCCCCCCCCCCCCCCCCCHHHHHHH...  
97  HHHHHHHHHHHHHHCCCCCCCCCHHHHHCCCCCCCCCCCCCEEEEE...  
98  EEEEEEEEEEEEEEEEEEHHHHHHHHHHCCCCCCCCHHHHHHHEEE...  
99  HHHHHHHHHEEEEEEEEEEEEEEEEEEHHHHHHHHHHHHHHHHCCC...  

[100 rows x 2 columns]

In [35]:
amino_acids = "ACDEFGHIKLMNPQRSTVWY"
aa_to_idx = {aa:i for i, aa in enumerate(amino_acids)}

# one hot encode the Sequence using the 20 Amino Acids as classes
def one_hot_encode_sequence(seq):
    X = np.zeros((len(seq), 20))
    for i, aa in enumerate(seq):
        if aa in aa_to_idx:
            X[i, aa_to_idx[aa]] = 1
        else:
            pass 
    return X
  
def sliding_window_features(seq, window):
    half = window // 2
    padded = "X"*half + seq + "X"*half

    samples = []
    for i in range(len(seq)):
        window_seq = padded[i:i+window]
        samples.append(one_hot_encode_sequence(window_seq).flatten())
    return np.array(samples)



In [ ]:
train_features = []
train_labels = []

test_features = []
test_labels = []


ss_labels = {'H':0, 'E':1, 'C':2}

window_size = 7

train_split = 80

### Train and Test datasets are create separately to avoid Data Leakages. ###

# Train dataset creation using the first 80 Sequences
for i in range(0, train_split):
    X = sliding_window_features(df['Sequence'][i], window=window_size)
    y = np.array([ss_labels[s] for s in df['Structure'][i]])

    for xi, yi in zip(X, y):    
        train_features.append(xi)
        train_labels.append(yi)

# Test dataset creation using the last 20 Sequences
for i in range(train_split, 100):
    X = sliding_window_features(df['Sequence'][i], window=window_size)
    y = np.array([ss_labels[s] for s in df['Structure'][i]])

    for xi, yi in zip(X, y):    
        test_features.append(xi)
        test_labels.append(yi)

In [37]:
train_features = np.array(train_features)
train_labels = np.array(train_labels)

test_features = np.array(test_features)
test_labels = np.array(test_labels)


train_features.shape, train_labels.shape, test_features.shape, test_labels.shape

((9343, 140), (9343,), (2182, 140), (2182,))

In [38]:
train_split = train_features.shape[0]/(train_features.shape[0]+test_features.shape[0])
print(f'Train Split as a Percentage: {round(train_split*100,2)}%')


Train Split as a Percentage: 81.07%


In [39]:
# Actual Train Split is closer to 80%. Since every sequence is not eqaul length, this small change can be expected

In [40]:
unique, counts = np.unique(train_labels, return_counts=True)
print('Trainig Data Class counts')
unique, counts, counts/sum(counts)

Trainig Data Class counts


(array([0, 1, 2]),
 array([3175, 3079, 3089]),
 array([0.33982661, 0.32955154, 0.33062186]))

In [41]:
unique, counts = np.unique(test_labels, return_counts=True)
print('Testing Data Class counts')
unique, counts, counts/sum(counts) 

Testing Data Class counts


(array([0, 1, 2]),
 array([705, 740, 737]),
 array([0.32309808, 0.33913841, 0.33776352]))

In [42]:
# Classes are not perfectly balanced, But they are within the vicinity of 33%.

In [43]:
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,           
    min_samples_leaf=5,     
    max_features='sqrt',
    class_weight='balanced', 
    random_state=42,
)

rf.fit(train_features, train_labels)

test_preds = rf.predict(test_features)

In [44]:
acc = accuracy_score(test_labels, test_preds)
print("Test Accuracy:", acc)

print("\nClassification report:")
print(classification_report(test_labels, test_preds, target_names=ss_labels.keys()))

Test Accuracy: 0.3235563703024748

Classification report:
              precision    recall  f1-score   support

           H       0.32      0.32      0.32       705
           E       0.32      0.34      0.33       740
           C       0.33      0.31      0.32       737

    accuracy                           0.32      2182
   macro avg       0.32      0.32      0.32      2182
weighted avg       0.32      0.32      0.32      2182



In [45]:
train_preds = rf.predict(train_features)
print("Train Accuracy:", accuracy_score(train_labels, train_preds))
print("Test Accuracy:",  accuracy_score(test_labels, test_preds))

Train Accuracy: 0.7072674729744194
Test Accuracy: 0.3235563703024748
